export const allProducts = [
  {
    productCode: 1,
    icons: {
      white: "../assets/silky-brand-albuquerque-shirt-white.png",
      red: "../assets/silky-brand-albuquerque-shirt-red.png",
      yellow: "../assets/silky-brand-albuquerque-shirt-yellow.png",
      blue: "../assets/silky-brand-albuquerque-shirt-blue.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Albuquerque Shirt",
    itemName: "albuquerque-shirt",
    price: 19.99,
    category: "shirts",
    colors: ["white", "yellow", "blue", "red"],
    color: "white",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 2,
    icons: {
      white: "../assets/silky-brand-albuquerque-shirt-white.png",
      red: "../assets/silky-brand-albuquerque-shirt-red.png",
      yellow: "../assets/silky-brand-albuquerque-shirt-yellow.png",
      blue: "../assets/silky-brand-albuquerque-shirt-blue.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Albuquerque Shirt",
    itemName: "albuquerque-shirt",
    price: 19.99,
    category: "shirts",
    colors: ["white", "yellow", "blue", "red"],
    color: "red",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 3,
    icons: {
      white: "../assets/silky-brand-albuquerque-shirt-white.png",
      red: "../assets/silky-brand-albuquerque-shirt-red.png",
      yellow: "../assets/silky-brand-albuquerque-shirt-yellow.png",
      blue: "../assets/silky-brand-albuquerque-shirt-blue.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Albuquerque Shirt",
    itemName: "albuquerque-shirt",
    price: 19.99,
    category: "shirts",
    colors: ["white", "yellow", "blue", "red"],
    color: "blue",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 4,
    icons: {
      white: "../assets/silky-brand-albuquerque-shirt-white.png",
      red: "../assets/silky-brand-albuquerque-shirt-red.png",
      yellow: "../assets/silky-brand-albuquerque-shirt-yellow.png",
      blue: "../assets/silky-brand-albuquerque-shirt-blue.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Albuquerque Shirt",
    itemName: "albuquerque-shirt",
    price: 19.99,
    category: "shirts",
    colors: ["white", "yellow", "blue", "red"],
    color: "yellow",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 5,
    icons: {
      white: "../assets/silky-brand-denver-pants-white.png",
      green: "../assets/silky-brand-denver-pants-green.png",
      yellow: "../assets/silky-brand-denver-pants/-ellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Denver Pants",
    itemName: "denver-pants",
    price: 39.99,
    category: "pants",
    colors: ["white", "yellow", "green"],
    color: "white",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 6,
    icons: {
      white: "../assets/silky-brand-denver-pants-white.png",
      green: "../assets/silky-brand-denver-pants-green.png",
      yellow: "../assets/silky-brand-denver-pants-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Denver Pants",
    itemName: "denver-pants",
    price: 39.99,
    category: "pants",
    colors: ["white", "yellow", "green"],
    color: "yellow",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 7,
    icons: {
      white: "../assets/silky-brand-denver-pants-white.png",
      green: "../assets/silky-brand-denver-pants-green.png",
      yellow: "../assets/silky-brand-denver-pants-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "Denver Pants",
    itemName: "denver-pants",
    price: 39.99,
    category: "pants",
    colors: ["white", "yellow", "green"],
    color: "green",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 8,
    icons: {
      white: "../assets/silky-brand-new-orleans-shoes-white.png",
      red: "../assets/silky-brand-new-orleans-shoes-red.png",
      yellow: "../assets/silky-brand-new-orleans-shoes-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "New Orleans Shoes",
    itemName: "new-orleans-shoes",
    price: 39.99,
    category: "shoes",
    colors: ["white", "yellow", "red"],
    color: "white",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 9,
    icons: {
      white: "../assets/silky-brand-new-orleans-shoes-white.png",
      red: "../assets/silky-brand-new-orleans-shoes-red.png",
      yellow: "../assets/silky-brand-new-orleans-shoes-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "New Orleans Shoes",
    itemName: "new-orleans-shoes",
    price: 39.99,
    category: "shoes",
    colors: ["white", "yellow", "red"],
    color: "red",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 10,
    icons: {
      white: "../assets/silky-brand-new-orleans-shoes-white.png",
      red: "../assets/silky-brand-new-orleans-shoes-red.png",
      yellow: "../assets/silky-brand-new-orleans-shoes-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "New Orleans Shoes",
    itemName: "new-orleans-shoes",
    price: 39.99,
    category: "shoes",
    colors: ["white", "yellow", "red"],
    color: "yellow",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 11,
    icons: {
      green: "../assets/silky-brand-san-diego-dress-green.png",
      yellow: "../assets/silky-brand-san-diego-dress-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "San Diego Dress",
    itemName: "san-diego-dress",
    price: 39.99,
    category: "dresses",
    colors: ["yellow", "green"],
    color: "yellow",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 12,
    icons: {
      green: "../assets/silky-brand-san-diego-dress-green.png",
      yellow: "../assets/silky-brand-san-diego-dress-yellow.png",
    },
    brand: "silky-brand",
    brandName: "Silky Brand",
    name: "San Diego Dress",
    itemName: "san-diego-dress",
    price: 39.99,
    category: "dresses",
    colors: ["yellow", "green"],
    color: "green",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 13,
    icons: {
      white: "../assets/fancy-brand-washington-dress-white.png",
      black: "../assets/fancy-brand-washington-dress-black.png",
      red: "../assets/fancy-brand-washington-dress-red.png",
      blue: "../assets/fancy-brand-washington-dress-blue.png",
    },
    brand: "fancy-brand",
    brandName: "Fancy Brand",
    name: "Washington Dress",
    itemName: "washington-dress",
    price: 399.99,
    category: "dresses",
    colors: ["white", "black", "red", "blue"],
    color: "white",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 14,
    icons: {
      white: "../assets/fancy-brand-washington-dress-white.png",
      black: "../assets/fancy-brand-washington-dress-black.png",
      red: "../assets/fancy-brand-washington-dress-red.png",
      blue: "../assets/fancy-brand-washington-dress-blue.png",
    },
    brand: "fancy-brand",
    brandName: "Fancy Brand",
    name: "Washington Dress",
    itemName: "washington-dress",
    price: 399.99,
    category: "dresses",
    colors: ["white", "black", "red", "blue"],
    color: "black",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 15,
    icons: {
      white: "../assets/fancy-brand-washington-dress-white.png",
      black: "../assets/fancy-brand-washington-dress-black.png",
      red: "../assets/fancy-brand-washington-dress-red.png",
      blue: "../assets/fancy-brand-washington-dress-blue.png",
    },
    brand: "fancy-brand",
    brandName: "Fancy Brand",
    name: "Washington Dress",
    itemName: "washington-dress",
    price: 399.99,
    category: "dresses",
    colors: ["white", "black", "red", "blue"],
    color: "red",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 16,
    icons: {
      white: "../assets/fancy-brand-washington-dress-white.png",
      black: "../assets/fancy-brand-washington-dress-black.png",
      red: "../assets/fancy-brand-washington-dress-red.png",
      blue: "../assets/fancy-brand-washington-dress-blue.png",
    },
    brand: "fancy-brand",
    brandName: "Fancy Brand",
    name: "Washington Dress",
    itemName: "washington-dress",
    price: 399.99,
    category: "dresses",
    colors: ["white", "black", "red", "blue"],
    color: "blue",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 17,
    icons: {
      white: "../assets/fancy-brand-philadelphia-shoes-white.png",
      red: "../assets/fancy-brand-philadelphia-shoes-red.png",
    },
    brand: "fancy-brand",
    brandName: "Fancy Brand",
    name: "Philadelphia Shoes",
    itemName: "philadelphia-shoes",
    price: 199.99,
    category: "shoes",
    colors: ["white", "red"],
    color: "white",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 18,
    icons: {
      white: "../assets/fancy-brand-philadelphia-shoes-white.png",
      red: "../assets/fancy-brand-philadelphia-shoes-red.png",
    },
    brand: "fancy-brand",
    brandName: "Fancy Brand",
    name: "Philadelphia Shoes",
    itemName: "philadelphia-shoes",
    price: 199.99,
    category: "shoes",
    colors: ["white", "red"],
    color: "red",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 19,
    icons: {
      white: "../assets/street-brand-miami-shirt-white.png",
      blue: "../assets/street-brand-miami-shirt-blue.png",
      green: "../assets/street-brand-miami-shirt-green.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "Miami Shirt",
    itemName: "miami-shirt",
    price: 29.99,
    category: "shirts",
    colors: ["white", "blue", "green"],
    color: "white",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 20,
    icons: {
      white: "../assets/street-brand-miami-shirt-white.png",
      blue: "../assets/street-brand-miami-shirt-blue.png",
      green: "../assets/street-brand-miami-shirt-green.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "Miami Shirt",
    itemName: "miami-shirt",
    price: 29.99,
    category: "shirts",
    colors: ["white", "blue", "green"],
    color: "blue",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 21,
    icons: {
      white: "../assets/street-brand-miami-shirt-white.png",
      blue: "../assets/street-brand-miami-shirt-blue.png",
      green: "../assets/street-brand-miami-shirt-green.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "Miami Shirt",
    itemName: "miami-shirt",
    price: 29.99,
    category: "shirts",
    colors: ["white", "blue", "green"],
    color: "green",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 22,
    icons: {
      black: "../assets/street-brand-detroit-pants-black.png",
      red: "../assets/street-brand-detroit-pants-red.png",
      blue: "../assets/street-brand-detroit-pants-blue.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "Detroit Pants",
    itemName: "detroit-pants",
    price: 59.99,
    category: "pants",
    colors: ["black", "blue", "red"],
    color: "black",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 23,
    icons: {
      black: "../assets/street-brand-detroit-pants-black.png",
      red: "../assets/street-brand-detroit-pants-red.png",
      blue: "../assets/street-brand-detroit-pants-blue.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "Detroit Pants",
    itemName: "detroit-pants",
    price: 59.99,
    category: "pants",
    colors: ["black", "blue", "red"],
    color: "blue",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 24,
    icons: {
      black: "../assets/street-brand-detroit-pants-black.png",
      red: "../assets/street-brand-detroit-pants-red.png",
      blue: "../assets/street-brand-detroit-pants-blue.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "Detroit Pants",
    itemName: "detroit-pants",
    price: 59.99,
    category: "pants",
    colors: ["black", "blue", "red"],
    color: "red",
    sizes: ["s", "m", "l", "xl"],
  },
  {
    productCode: 25,
    icons: {
      black: "../assets/street-brand-new-york-shoes-black.png",
      red: "../assets/street-brand-new-york-shoes-red.png",
      green: "../assets/street-brand-new-york-shoes-green.png",
      yellow: "../assets/street-brand-new-york-shoes-yellow.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "New York Shoes",
    itemName: "new-york-shoes",
    price: 99.99,
    category: "shoes",
    colors: ["black", "yellow", "red", "green"],
    color: "black",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 26,
    icons: {
      black: "../assets/street-brand-new-york-shoes-black.png",
      red: "../assets/street-brand-new-york-shoes-red.png",
      green: "../assets/street-brand-new-york-shoes-green.png",
      yellow: "../assets/street-brand-new-york-shoes-yellow.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "New York Shoes",
    itemName: "new-york-shoes",
    price: 99.99,
    category: "shoes",
    colors: ["black", "yellow", "red", "green"],
    color: "yellow",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 27,
    icons: {
      black: "../assets/street-brand-new-york-shoes-black.png",
      red: "../assets/street-brand-new-york-shoes-red.png",
      green: "../assets/street-brand-new-york-shoes-green.png",
      yellow: "../assets/street-brand-new-york-shoes-yellow.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "New York Shoes",
    itemName: "new-york-shoes",
    price: 99.99,
    category: "shoes",
    colors: ["black", "yellow", "red", "green"],
    color: "red",
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    productCode: 28,
    icons: {
      black: "../assets/street-brand-new-york-shoes-black.png",
      red: "../assets/street-brand-new-york-shoes-red.png",
      green: "../assets/street-brand-new-york-shoes-green.png",
      yellow: "../assets/street-brand-new-york-shoes-yellow.png",
    },
    brand: "street-brand",
    brandName: "Street Brand",
    name: "New York Shoes",
    itemName: "new-york-shoes",
    price: 99.99,
    category: "shoes",
    colors: ["black", "yellow", "red", "green"],
    color: "green",
    sizes: ["7", "8", "9", "10", "11"],
  },
]